server:
  port: 8080
  servlet:
    context-path: /bankmanagesystem
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    username: kgb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql://116.62.12.63:3308/bank_management_sys?useUnicode=true&allowMultiQueries=true&useAffectedRows=true&characterEncoding=UTF-8&serverTimezone=GMT
  jackson:
    serialization:
      write-dates-as-timestamps: true #返回时间戳为long型

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.gdut.bankmanagesystem.entity

  configuration:
    default-executor-type: simple

#日志
logging:
  file:
    path: D:/logs/bankmanagesystem
  level:
    root: info

